name: portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  flutter_staggered_animations: ^1.0.0
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/SkyForgeIcon.png"